name: Deploy SoundPass to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar código en VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/concert-tickets
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # Aquí pondremos el reinicio del servicio de Flask después